"""create beam yard core tables

Revision ID: a006ca44c863
Revises: e13617171978
Create Date: 2026-08-31 11:49:19.636619

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'a006ca44c863'
down_revision: Union[str, Sequence[str], None] = 'e13617171978'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('beam_type',
    sa.Column('type_code', sa.String(length=64), nullable=False, comment='梁型稳定业务编码'),
    sa.Column('type_name', sa.String(length=128), nullable=False, comment='梁型名称'),
    sa.Column('length_mm', sa.Numeric(precision=12, scale=3), nullable=True, comment='标称长度，单位mm'),
    sa.Column('width_mm', sa.Numeric(precision=12, scale=3), nullable=True, comment='标称宽度，单位mm'),
    sa.Column('height_mm', sa.Numeric(precision=12, scale=3), nullable=True, comment='标称高度，单位mm'),
    sa.Column('weight_kg', sa.Numeric(precision=12, scale=3), nullable=True, comment='标称质量，单位kg'),
    sa.Column('description', sa.String(length=500), nullable=True, comment='梁型描述'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='技术主键'),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False, comment='更新时间（UTC）'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beam_type')),
    sa.UniqueConstraint('type_code', name=op.f('uq_beam_type_type_code'))
    )
    op.create_table('yard_area',
    sa.Column('area_code', sa.String(length=64), nullable=False, comment='区域稳定业务编码'),
    sa.Column('area_name', sa.String(length=128), nullable=False, comment='区域名称'),
    sa.Column('area_type', sa.String(length=32), nullable=False, comment='区域类型代码'),
    sa.Column('parent_id', sa.BigInteger(), nullable=True, comment='父区域ID'),
    sa.Column('sort_order', sa.Integer(), server_default=sa.text('0'), nullable=False, comment='展示排序值'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='技术主键'),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False, comment='更新时间（UTC）'),
    sa.ForeignKeyConstraint(['parent_id'], ['yard_area.id'], name=op.f('fk_yard_area_parent_id_yard_area'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_yard_area')),
    sa.UniqueConstraint('area_code', name=op.f('uq_yard_area_area_code'))
    )
    op.create_index(op.f('ix_yard_area_parent_id'), 'yard_area', ['parent_id'], unique=False)
    op.create_table('beam_position',
    sa.Column('position_code', sa.String(length=64), nullable=False, comment='梁位稳定业务编码'),
    sa.Column('position_name', sa.String(length=128), nullable=True, comment='梁位名称'),
    sa.Column('area_id', sa.BigInteger(), nullable=False, comment='所属梁场区域ID'),
    sa.Column('x_mm', sa.Numeric(precision=14, scale=3), nullable=True, comment='场地X坐标，单位mm'),
    sa.Column('y_mm', sa.Numeric(precision=14, scale=3), nullable=True, comment='场地Y坐标，单位mm'),
    sa.Column('z_mm', sa.Numeric(precision=14, scale=3), nullable=True, comment='场地Z坐标，单位mm'),
    sa.Column('is_active', sa.Boolean(), nullable=False, comment='是否启用'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='技术主键'),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False, comment='更新时间（UTC）'),
    sa.ForeignKeyConstraint(['area_id'], ['yard_area.id'], name=op.f('fk_beam_position_area_id_yard_area'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beam_position')),
    sa.UniqueConstraint('position_code', name=op.f('uq_beam_position_position_code'))
    )
    op.create_index(op.f('ix_beam_position_area_id'), 'beam_position', ['area_id'], unique=False)
    op.create_table('beam',
    sa.Column('beam_code', sa.String(length=64), nullable=False, comment='梁稳定业务编号'),
    sa.Column('beam_name', sa.String(length=128), nullable=True, comment='梁名称'),
    sa.Column('beam_type_id', sa.BigInteger(), nullable=False, comment='梁型ID'),
    sa.Column('current_position_id', sa.BigInteger(), nullable=True, comment='当前梁位ID'),
    sa.Column('status', sa.String(length=32), nullable=False, comment='梁当前状态代码'),
    sa.Column('production_date', sa.Date(), nullable=True, comment='生产日期'),
    sa.Column('remark', sa.String(length=500), nullable=True, comment='备注'),
    sa.Column('id', sa.BigInteger(), autoincrement=True, nullable=False, comment='技术主键'),
    sa.Column('created_at', mysql.DATETIME(fsp=6), nullable=False, comment='创建时间（UTC）'),
    sa.Column('updated_at', mysql.DATETIME(fsp=6), nullable=False, comment='更新时间（UTC）'),
    sa.ForeignKeyConstraint(['beam_type_id'], ['beam_type.id'], name=op.f('fk_beam_beam_type_id_beam_type'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['current_position_id'], ['beam_position.id'], name=op.f('fk_beam_current_position_id_beam_position'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_beam')),
    sa.UniqueConstraint('beam_code', name=op.f('uq_beam_beam_code')),
    sa.UniqueConstraint('current_position_id', name=op.f('uq_beam_current_position_id'))
    )
    op.create_index(op.f('ix_beam_beam_type_id'), 'beam', ['beam_type_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_beam_beam_type_id'), table_name='beam')
    op.drop_table('beam')
    op.drop_index(op.f('ix_beam_position_area_id'), table_name='beam_position')
    op.drop_table('beam_position')
    op.drop_index(op.f('ix_yard_area_parent_id'), table_name='yard_area')
    op.drop_table('yard_area')
    op.drop_table('beam_type')
    # ### end Alembic commands ###
